.travis.yml:
  sudo: true
  services:
  - docker
  addons:
    apt:
      packages:
      - debhelper # required for trusty VM
      - cmake
      - libgeoip-dev
      - protobuf-compiler
  install:
    - cd $SNAP_PLUGIN_SOURCE
    - make
  env:
    global:
      - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
      - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
    matrix:
      - TEST=unit
      - TEST=integration
  deploy:
    access_key_id: AKIAINMB43VSSPFZISAA
    secret_access_key:
      secure: 7QXngtDKus/SMa3JYKTBkc4usMw4W2NfBPOd8LGkGIu8TyfGq89avWu4CFWQDEN4l62qBQNp5Vs2KRd7FQMhwd5faboq8j0OVe7IRMHBlaS+1BqfZmKZEEWsUJ6mEy/CFgkQIGqDxv9eoL3TjPgCevCXfvMuR1mV3VAqe2iZGROJDzwFzu5+b2bMwwOWq/cvl9ojfeQSXrZX1bu1hcl1AC1Y1w3p03vFj0K/9t87e+vU99G/0td1NDUjzcLpHoXZvoxlmGG9O6jCJAVTP5fLbu0ogWcrgzRhxyBz+jyZyemv3/ywFFG6y9H8UqoDB2MHmQxPUkzg99mkbzIXZdiG5gfRrv753TYlwX9Q0F5+XW9/QP+mx+eb05sQYAJzqaq0m53b2s5ylEyrFDGa3iVJGfuexgGlO2H6Lm4DihWkkxMAjdDdFDyADymv6pXyM41syvyyjdpR3mj2E6i0tPJnlNg+TNqhIj4Vzq8JsRcngmnXx4608S6Tc44zkwV+zBKhlnGC0B6eOht1ndVs7FVDvAgdV7bG75mjylm4CrNVYpL64uVXQlQogn9A0KpuqJqIfAAHYGv3hRVtpApUPGMgPaKrrYA9Hjjs3WeRdhxnwJQgacpY/1LC+3YDfefObmm2GKR8yWmF7ZU2p9N4UbS6jeFpStiwMAI5RpdgQE1THNo=
    api_key:
      secure: ME2p0m9o5k5+EoN3kbKjPjnpwMNZGu66BdwR1tteRKXRaE4J2xFl7WeRqwvWZ51XMy2AsS0Ef6FeKkxbDKZnyTdsRuk3wWqCSX23suBJhTXS+DVCKRhXn66thN6kbDFZKGghTQeOrQCPJG7jIxzHdKXG6OgrguIrX8ijfgw0NHPLLN8qOXbmfB8bzi2OI1YwTdtZzmyFbp0u3FnC1T6jku+5mWvOWgcMaBeyVtEp/abNLENfLCmKEDzSAwmjljUx3D3mXUFhsz6JvWqxXG88CPmOwIJfZmLIaZTIOdkGh2y1eXUr/H9CXCJ5FTjIjPjAe9aeKdHuHwy8WJcUdVLYvWoA/QkvZqkOT8jU+5pB7j3PJ8kYpXkmYWaAr9nLYoARNtObVtowT5USSipdugsnMNafggvXRpCiLY8YVesZ7jNIyn+FAhxRE3NYD6ii0c2lBkXx26rO1YQHg2qeroBQuS6o2tsRv4iHMzZVzS06z82f+F2aZGIq0EQIoDBXC290WWH4wyK4TlGCwqvFf+kLkUeLpw2wsRUjh2Zic7rbhghBJm6Dk+OKg4s2DPqmOzyn/mYIyOD253Wb08KymzDhqnTxcWEDRoBF/+PlSEz2iik9vUryBulqzSybdiO+JJZiR+/TyMoDLNlppZCO30tzl4thbZKcvS0uixAO8IlH974=
scripts/build.sh:
   unmanaged: true
scripts/test.sh:
  unmanaged: true
Makefile:
  unmanaged: true
